

export const CHANGE_EAF= 'CHANGE_EAF';
export const CHANGE_SCALE_FACTORS = 'CHANGE_SCALE_FACTORS';
export const CHANGE_FUNCTION_POINT = 'CHANGE_FUNCTION_POINT';
export const CHANGE_KLOC = 'CHANGE_KLOC';
// export const GET_SUITABLE_STAFF = 'GET_SUITABLE_STAFF';
// export const CACULATE_EAF = 'CACULATE_EAF';