export const CHANGE_LOGIN_FORM = 'CHANGE_LOGIN_FORM';
export const CHANGE_REGISTER_FORM = 'CHANGE_REGISTER_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';